### ISSUE TITLE
ErrorException in DB2Grammer.php: Missing Argument

### ISSUE THREAD

**Issue by sarahkemp** [cooperl22/laravel-db2#29]
I updated today to ~5.4 and I get this error now whenever I open a page that uses my ibmi connection:

```
ErrorException in DB2Grammar.php line 45:
Missing argument 1 for Cooperl\Database\DB2\Schema\Grammars\DB2Grammar::__construct(), called in /var/www/lara/vendor/cooperl/laravel-db2/src/DB2Connection.php on line 114
```

I see the latest commit changed this. Is it working as intended?

**Comment by cooperl22** [comment]
Hi.

Can you please update the package?

It should be OK now.

Ple&ase read the README because yes indeed I've changed config. No need to set all the ODBC keywords anymore, just those you need.

**Comment by sarahkemp** [comment]
The update fixes it, thank you.

Thank you for providing and continuing to improve the package!
