### ISSUE TITLE
Symfony \ Component \ Debug \ Exception

### ISSUE THREAD

**Issue by gbryant200** [cooperl22/laravel-db2#37]
Undefined class constant 'I5_ATTR_DBC_SYS_NAMING'

All the PDO:I5 attributes are listed as errors; Reference constant is not found in class.

Is there a typo or am I missing something?  New to Laravel.

Thanks

**Comment by cooperl22** [comment]
Theses constants are for pdo_ibm driver only. If you use ODBC you can remove them from the config...

**Comment by gbryant200** [comment]
I have the ibm_pdo and db2_ibm extensions installed for PHP 7.1 on my LAMP stack.  I can connect to our db2 on our AIX system.  I can connect using the db2 cli and using direct pdo in PHP.

Does the db2_ibmi_ibm driver use the php extension or is this only for db2 on an IBM i system?  Do I connect using database' => 'WRKRDBDIRE entry',  where 'entry' is the db2 catalog setup in the instance?  Is the 'driverName' significant?  What would it be for pdo_ibm?

Thanks.

**Comment by cooperl22** [comment]
This package only relies on PDO connections so you need to use db2_ibmi_ibm for pdo_ibm php extension. ibm_db2 is not compatible with PDO.
