### ISSUE TITLE
Laravel 5.8 Compatibility?

### ISSUE THREAD

**Issue by lettucereviews** [cooperl22/laravel-db2#52]
Hi, will this be made compatible with Laravel 5.8? I'm getting the following when doing a composer update

    - cooperl/laravel-db2 5.7.0 requires laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev].
    - cooperl/laravel-db2 5.7.1 requires illuminate/database 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

**Comment by renux91** [comment]
I need this update too !

**Comment by lettucereviews** [comment]
Even a short tutorial on how the extension works and how we can keep it up to date and debug it would be amazing, if the owner decides not to support this anymore.

**Comment by cooperl22** [comment]
Version 5.8.0 released!
