### ISSUE TITLE
Error when laravel running on linux

### ISSUE THREAD

**Issue by banibanc** [cooperl22/laravel-db2#54]
Hi,

I'm trying to use this package to connect to a i series db2 server from a laravel application hosted on a linux server (centos).

I'm using db2_ibmi_ibm driver : 

![2019-05-09_114221](https://user-images.githubusercontent.com/5338661/57450057-bf636d00-725d-11e9-8335-d923893765d1.png)

I had a first problem with these PDO constants in the options :

PDO::I5_ATTR_DBC_SYS_NAMING => false,
PDO::I5_ATTR_COMMIT => PDO::I5_TXN_NO_COMMIT,
PDO::I5_ATTR_JOB_SORT => false,
PDO::I5_ATTR_DBC_LIBL => '',
PDO::I5_ATTR_DBC_CURLIB => '',

> Undefined class constant 'I5_ATTR_DBC_SYS_NAMING'

When I commented theses lines, I got this error : 

> SQLSTATE[42601]: Syntax error: -104 [IBM][CLI Driver][AS] SQL0104N An unexpected token "<END-OF-STATEMENT>" was found following "". Expected tokens may include: "( + - ? : DAY INF NAN RID ROW RRN". SQLSTATE=42601 (SQLNumResultCols[-104] at /root/PDO_IBM-1.3.6/ibm_driver.c:153) (SQL: select * from )

Is there something special to do to make it work on that configuration ? Meaning laravel running on a linux server.

**Comment by banibanc** [comment]
I found the error and it wasn't related to your package.

It works great, thanks !

**Comment by sylwn** [comment]
Hello @banibanc,

I have a similar issue. I am unable to use the constants PDO::I5_ATTR_DBC_SYS_NAMING and PDO::I5_ATTR_DBC_LIBL when using pdo_ibm.

I am getting the following error:

Fatal error: Uncaught Error: Undefined class constant 'I5_ATTR_DBC_SYS_NAMING' in /www/xxx/xxx/xxx.php:30 Stack trace: #0 {main} thrown in /www/xxx/xxx/xxx.php on line 30

My set up is a docker container with Debian 9 and php7.1. The pdo_ibm.so version 1.3.4 (also tried 1.3.6) is properly installed and enabled with php.
My code look like the following:

$db = new PDO("ibm:*LOCAL", $user, $password, array(
  PDO::ATTR_PERSISTENT => true,
  PDO::ATTR_AUTOCOMMIT => true,
  PDO::I5_ATTR_DBC_SYS_NAMING => true,
  PDO::I5_ATTR_DBC_LIBL => "SHZDEV",
));

How did you get the contants to work with your linux?

**Comment by banibanc** [comment]
The constants weren't the issue here. I think the problem was that the ip from my linux server wasn't whitelisted in the db2 server. Once it was I didn't have the error anymore.

**Comment by sylwn** [comment]
@banibanc 
Ok but you said in your very first message that you had this issue and I quote:
"
I had a first problem with these PDO constants in the options :

PDO::I5_ATTR_DBC_SYS_NAMING => false,
PDO::I5_ATTR_COMMIT => PDO::I5_TXN_NO_COMMIT,
PDO::I5_ATTR_JOB_SORT => false,
PDO::I5_ATTR_DBC_LIBL => '',
PDO::I5_ATTR_DBC_CURLIB => '',

Undefined class constant 'I5_ATTR_DBC_SYS_NAMING'
"

How did you fix that problem?

**Comment by banibanc** [comment]
Commented them
