### ISSUE TITLE
Laravel 6.0 compatibility

### ISSUE THREAD

**Issue by robert1233** [cooperl22/laravel-db2#57]
Hi! Would love if this was updated to Laravel 6.0. Thank you for all the hard work!

**Comment by wjonkerhulst** [comment]
Hey great project. Would also love to see support for laravel 6.0, also for the laravel-ibmi project.

**Comment by wjonkerhulst** [comment]
You can use these if needed.
DB2 Connetor for Laravel 6.0
- https://github.com/wjonkerhulst/laravel-db2

IBMi Toolkit
- https://github.com/wjonkerhulst/laravel-ibmi

**Comment by wjonkerhulst** [comment]
> You can use these if needed.
> DB2 Connetor for Laravel 6.0
> 
> * https://github.com/wjonkerhulst/laravel-db2
> 
> IBMi Toolkit
> 
> * https://github.com/wjonkerhulst/laravel-ibmi

Please use this only for testing. I would recommend to waith for a fix from cooperl22 if you want to start using this package in production.

**Comment by cooperl22** [comment]
✔️
