### ISSUE TITLE
Problem (and temporary solution) connection to System i (AS400) DB2 using db2_ibmi_odbc

### ISSUE THREAD

**Issue by RiccardoFrancescato** [cooperl22/laravel-db2#60]
I have setted all the parameters in the connection file, leaving the standard values.
Once i try to query the database, the connection fail with the following error.
```
PDOException
SQLSTATE[42000]: Syntax error or access violation: 0 [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLPrepare[0] at /builddir/build/BUILD/php-7.3.14/ext/pdo_odbc/odbc_driver.c:204)
```
I have debugged a bit the code following the stack trace.
I have found that the problem is not the DSN (i have tested the string composed by laravel-db2 with a plain php PDO call) but the code used to set the default schema. 
The file is: `vendor/cooperl/laravel-db2/src/Connectors/DB2Connector.php:29`
The piece of code that throws the error is:
```
if (isset($config['schema'])) {

            $schema = $config['schema'];

            $connection->prepare('set schema ' . $schema)

                       ->execute();

        }
```
May solution consists of commenting the `'schema' => '',` element in the connection configuration.
In my opinion this is a temporary solution to the problem. Probability the problem is caused by the query builder engine that puts ";" ath the end of the query string.

**Comment by hmrneves1** [comment]
hello, could you please share you configuration settings? I'm also trying to connect laravel to AS400 with a centos8 server. Always getting 

`SQLSTATE[08001] SQLDriverConnect: -30081 [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "127.0.0.1". Communication function detecting the error: "connect". Protocol specific error code(s): "111", "*", "*". SQLSTATE=08001`

Regards!!

**Comment by RiccardoFrancescato** [comment]
I have solved the issue using IBM iAccess client for linux 
The installation commands are:
```
yum install -y unixODBC unixODBC-devel ibm-iaccess-1.1.0.13-1.0.x86_64.rpm
cd /usr/lib64/
ln -s libodbcinst.so.2 /usr/lib64/libodbcinst.so.1
cd /usr/lib
ln -s libodbcinst.so.2 /usr/lib/libodbcinst.so.1
```
The `Ibm-iaccess-1.1.0.13-1.0.x86_64.rpm` package can be downloaded from IBM website: https://www.ibm.com/support/pages/obtaining-ibm-i-access-client-solutions
The official IBM book is availabel at: https://www.ibm.com/support/pages/sites/default/files/inline-files/$FILE/accessing_ibm_db2_for_i_data_from_linux_applications_running_on_IBMi.pdf
