### ISSUE TITLE
Update for PHP 8.0

### ISSUE THREAD

**Issue by keganlester** [cooperl22/laravel-db2#78]
Is there any chance this project is in the works to be compatible with PHP 8.0. This will allow the use of Octane.

**Comment by wjonkerhulst** [comment]
I think the only problem is the version limitation in de composer.json. 

I have been running a local (slightly) modified version on PHP 8.0 for over 9 months without any problems.

**Comment by chrisdicarlo** [comment]
I opened a PR for this: #81
